#!/bin/bash
if [[ "$1" == "secret" && "$2" == "list" ]]; then
  echo '[{"id":"id1","name":"SECRET1"},{"id":"id2","name":"SECRET2"}]'
elif [[ "$1" == "secret" && "$2" == "get" ]]; then
  if [[ "$3" == "id1" ]]; then
    echo "value1"
  elif [[ "$3" == "id2" ]]; then
    echo "value2"
  fi
fi
